### ISSUE TITLE
multi objects

### ISSUE THREAD

**Issue by hhhh0** [guchengxi1994/mask2json#1]
Does it support multiple objects?

**Comment by guchengxi1994** [comment]
it does not support multiple objects yet. But i think it's not complex.

i think the key point is how to get the outlining points of your objects via opencv(cv2.approxPolyDP) 
 and make sure each object is NOT connected to others.

i will add this part at the weekend or you can have a try by your self.

**Comment by hhhh0** [comment]
thanks a lot!
