### ISSUE TITLE
mask 2 json

### ISSUE THREAD

**Issue by bberry25** [guchengxi1994/mask2json#30]
Hi, thanks for the code.
I have a mask (binary file) and original image. 
How can I change it to JSON file ? I tried run the script in ur guide. But it's failed to get the information of area value 1 in mask file.

**Comment by guchengxi1994** [comment]
Thanks for issuing.
you can follow this script for converting masks to jsons.  [https://github.com/guchengxi1994/mask2json/blob/test/test_scripts/mask2json.py](url)

also, following codes maybe helpful.

```
from convertmask.utils.methods import getMultiShapes

imgPath = 'D:\\testALg\\mask2json\\mask2json\\static\\multi_objs_test.jpg'
maskPath = 'D:\\testALg\\mask2json\\mask2json\\static\\multi_objs_json\\label.png'
savePath = 'D:\\testALg\\mask2json\\mask2json\\static\\multi_objs_json\\1109\\'
yamlPath = 'D:\\testALg\\mask2json\\mask2json\\static\\multi_objs_json\\info.yaml'
getMultiShapes.getMultiShapes(imgPath, maskPath, savePath, yamlPath)  # with yaml

getMultiShapes.getMultiShapes(imgPath, maskPath, savePath)  # without yaml
```

with a yaml file or without a yaml file is very different, you can test by yourself.

**Comment by bberry25** [comment]
Thanks for the reply, but the url is broken. I'll appreciate if you refresh the url.

I have a question with yaml file. Is it created by some script or which script I can create that file in your code file?

**Comment by guchengxi1994** [comment]
you can copy the url and open it in your browser, it works for me. Otherwise, you can copy the code into your script , change your file path and have a try.
The yaml file is a file saves the label information like this.

```
label_names:
  _background_: 0
  fruit1: 1
  fruit2: 2
  fruitn: 3
```

Besides, those files in my script/code can be found in the 'static' folder.

**Comment by guchengxi1994** [comment]
you can create the yaml file by yourself, just like i posted.
