### ISSUE TITLE
are you available

### ISSUE THREAD

**Issue by seekingdeep** [guchengxi1994/mask2json#32]
@guchengxi1994 hi,
i have a task dealing with masks,
are you available for freelancing?
what is your email so i can discuss in more detail

**Comment by guchengxi1994** [comment]
i am working in a company but i am free on weekends and at nights， so if you have some problem ,you can email me via this address  guchengxi1994@qq.com , i will try my best to help.

**Comment by seekingdeep** [comment]
i should contact you by email tomorrow, i have a task for you. so be ready
