### ISSUE TITLE
ERROR mask2json

### ISSUE THREAD

**Issue by siwalex** [guchengxi1994/mask2json#39]
python mask2json.py
Traceback (most recent call last):
  File "mask2json.py", line 15, in <module>
    getMultiShapes.getMultiShapes(imgPath, maskPath, savePath)  # without yaml
  File "C:\Users\Siwal\AppData\Local\Programs\Python\Python37\lib\site-packages\convertmask\utils\getMultiShapes.py", line 229, in getMultiShapes
    raise FileNotFoundError('mask/labeled image not found')
FileNotFoundError: mask/labeled image not found

**Comment by guchengxi1994** [comment]
it seems that your file path is different from mine.  in this script, these files should be located at this filepath:
` 
    imgPath = 'D:\\testALg\\mask2json\\mask2json\\static\\multi_objs_test.jpg'

    maskPath = 'D:\\testALg\\mask2json\\mask2json\\static\\multi_objs_json\\label.png'

    savePath = 'D:\\testALg\\mask2json\\mask2json\\static\\multi_objs_json\\1109\\'

    yamlPath = 'D:\\testALg\\mask2json\\mask2json\\static\\multi_objs_json\\info.yaml'`

you should check whether you have this files

**Comment by siwalex** [comment]
hello,

i have all the files (i dowloaded your github zip)

i changed in E:\Mega\Alexandre\car_dataset\mask2json\test_scripts\mask2json.py lines 92 to 95 by :

    imgPath = 'E:\\Mega\\Alexandre\\car_datase\\mask2json\\static\\multi_objs_test.jpg'
    maskPath = 'E:\\Mega\\Alexandre\\car_datase\\mask2json\\static\\multi_objs_json\\label.png'
    savePath = 'E:\\Mega\\Alexandre\\car_datase\\mask2json\\static\\multi_objs_json\\1109\\'
    yamlPath = 'E:\\Mega\\Alexandre\\car_datase\\mask2json\\static\\multi_objs_json\\info.yaml'

and have this error :

λ python mask2json.py
Traceback (most recent call last):
  File "mask2json.py", line 98, in <module>
    getMultiShapes.getMultiShapes(imgPath, maskPath, savePath)  # without yaml
  File "..\convertmask\utils\methods\getMultiShapes.py", line 233, in getMultiShapes
    raise FileNotFoundError('mask/labeled image not found')
FileNotFoundError: mask/labeled image not found

**Comment by guchengxi1994** [comment]
![mask2json](https://user-images.githubusercontent.com/33513462/129292787-a85599f4-98c7-4d80-b189-d7e9bf75ebc8.gif)

I tested on my pc it worked well...

I noticed that you install this repo by pip, but the version on pypi has not been updated for a long time. That may be the reason you cannot run this script. It is my fault ,sorry about that. To deal with this problem, you can git clone this repo, switch to the test branch and try again.
