### ISSUE TITLE
test_imgAug  affedMask = cv2.warpAffine(mask, mat, (imgShape[1], imgShape[0]))

### ISSUE THREAD

**Issue by monkeycc** [guchengxi1994/mask2json#47]
```
python test_imgAug.py
ERROR argument should be a bytes-like object or ASCII string, not 'NoneType' (convert.py:102)
imgEncode is deprecated under 0.5.3.
WARNING rotation may cause salt-and-pepper noise. in order to solve this issue, small objects may be missing! (imgAug.py:464)
ERROR argument should be a bytes-like object or ASCII string, not 'NoneType' (convert.py:102)
Traceback (most recent call last):
  File "test_imgAug.py", line 37, in <module>
    imgRotation(imgPath, labelPath)
  File "..\convertmask\utils\auglib\imgAug.py", line 495, in imgRotation
    affedMask = cv2.warpAffine(mask, mat, (imgShape[1], imgShape[0]))
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:2595: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'cv::warpAffine'
```
labelme\examples\instance_segmentation\data_annotated\2011_000003.jpg
labelme\examples\instance_segmentation\data_annotated\2011_000003.json

![2011_000003](https://user-images.githubusercontent.com/6490927/176993087-5bb902f5-df7e-47ee-8e57-2f0bc0846033.jpg)

**Comment by guchengxi1994** [comment]
I downloaded your image and made a test, it is good for me.
![20220702](https://user-images.githubusercontent.com/33513462/176999268-cf3d7216-c28f-4da2-825c-190005f87e5e.gif)

I noticed that you are using v0.5.3, which is not the latest version, I thikn you clone this repo and use the latest version may help.

Besides, there may be a small problem you should pay attension.
![捕获](https://user-images.githubusercontent.com/33513462/176999382-114f5bca-b7cb-4c47-a58f-8114e88d33f0.PNG)

../utils/json2mask/convert_with_label.py  line 184 should modified like this.(this is a bug)
