### ISSUE TITLE
test_imgAug How to cycle catalog pictures

### ISSUE THREAD

**Issue by monkeycc** [guchengxi1994/mask2json#48]
test_imgAug.py

How to cycle catalog pictures

Now it can only be read one by one

How to batch read folder directory pictures

I found the name fixed
`mask2json\convertmask\utils\auglib\imgAug.py`
Simple modification
`fileName = str(''.join(random.sample(string.ascii_letters + string.digits, 8)))`

It should be more reasonable

**Comment by guchengxi1994** [comment]
usually, I use ```glob``` to get all files in a folder. I will consider about it , thanks for your suggestion.
