### ISSUE TITLE
Mask2json cannot recognize multiple labels

### ISSUE THREAD

**Issue by updatelse** [guchengxi1994/mask2json#57]
Why does the output json file have only one label? Does this code only recognize the single label of the mask?
Here's my data：
 mask pic:
![2056](https://user-images.githubusercontent.com/72791802/190615088-fb558805-8b90-4c68-8d31-db767fce53b2.png)

label_names:
![image](https://user-images.githubusercontent.com/72791802/190614361-3f69d9b8-d746-4756-90a7-07e5eebbc81e.png)

the output json:
![image](https://user-images.githubusercontent.com/72791802/190615401-afb11443-117c-4aec-b53d-0d6943e60408.png)

I look forward to receiving guidance, thank you ！

**Comment by guchengxi1994** [comment]
@updatelse I downloaded the image and make a test, I think this problem is your labels and your masks are not match.
```python
import numpy as np
import cv2

imgPath = "D:\\github_repo\\ttt\\190615088-fb558805-8b90-4c68-8d31-db767fce53b2.png"
img = cv2.imread(imgPath)

print(np.max(img))
print(np.unique(img))
```
the result is 
![image](https://user-images.githubusercontent.com/33513462/190835010-430546da-ec7d-42c4-b5c1-59bd4ff33c53.png)


There is only one label in this case, I think maybe you should ckeck your mask images and make some modifications.

Besides, it is very strange that I cannot open this image with `skimage`.
```python
from skimage import io
imgPath = "D:\\github_repo\\ttt\\190615088-fb558805-8b90-4c68-8d31-db767fce53b2.png"
i2 = io.imread(imgPath)
```
![image](https://user-images.githubusercontent.com/33513462/190835093-9d732a6f-a7a8-4a5c-a88f-f3ca76996dd8.png)

can you tell me how the image generated?

**Comment by updatelse** [comment]
> There is only one label in this case, I think maybe you should ckeck your mask images and make some modifications.

My mask image is a png color image with 8-bit depth. The PIL method is used for pretreatment.
Because I am carrying out unet image segmentation, its mask image must be 8-bit deep. However, I can't find the json file at the moment, so I want to reverse generate the json file from the mask image.
I tried to convert 8-bit color to PIL 24 bit color, but there was only a single label.
There are original images, mask images and labels file in the following link. I would be grateful if you would like to share with me your handling methods!
links：https://pan.baidu.com/s/1gS6h_FZaIjXCTfHKE3hxXg?pwd=iu76 
password：iu76

**Comment by updatelse** [comment]
> @updatelse I downloaded the image and make a test, I think this problem is your labels and your masks are not match.
> 
> ```python
> import numpy as np
> import cv2
> 
> imgPath = "D:\\github_repo\\ttt\\190615088-fb558805-8b90-4c68-8d31-db767fce53b2.png"
> img = cv2.imread(imgPath)
> 
> print(np.max(img))
> print(np.unique(img))
> ```
> 
> the result is ![image](https://user-images.githubusercontent.com/33513462/190835010-430546da-ec7d-42c4-b5c1-59bd4ff33c53.png)
> 
> There is only one label in this case, I think maybe you should ckeck your mask images and make some modifications.
> 
> Besides, it is very strange that I cannot open this image with `skimage`.
> 
> ```python
> from skimage import io
> imgPath = "D:\\github_repo\\ttt\\190615088-fb558805-8b90-4c68-8d31-db767fce53b2.png"
> i2 = io.imread(imgPath)
> ```
> 
> ![image](https://user-images.githubusercontent.com/33513462/190835093-9d732a6f-a7a8-4a5c-a88f-f3ca76996dd8.png)
> 
> can you tell me how the image generated?

My mask image is a png color image with 8-bit depth. The PIL method is used for pretreatment.
Because I am carrying out unet image segmentation, its mask image must be 8-bit deep. However, I can't find the json file at the moment, so I want to reverse generate the json file from the mask image.
I tried to convert 8-bit color to PIL 24 bit color, but there was only a single label.
There are original images, mask images and labels file in the following link. I would be grateful if you would like to share with me your handling methods!
links：https://pan.baidu.com/s/1gS6h_FZaIjXCTfHKE3hxXg?pwd=iu76 
password：iu76

**Comment by guchengxi1994** [comment]
@updatelse 抱歉回复晚了，这个问题我已经知道是什么情况了。
首先，你上传mask标注图像是三通道的，不是单通道的，每个通道一共两个数值，要么是0，要么是128.
![image](https://user-images.githubusercontent.com/33513462/192701872-dad22e8b-1254-443b-8a4c-78565e5cec09.png)
所以标注图像看上去才是彩色的。

解决方案的话稍微有点复杂，你需要遍历三个通道，然后把每个通道不为0的区域提取出来。比如，`r[0][0] != 0`，那么你就需要将这一部分取出来，作为一个类；同理g,b

但是这么做会有一个问题，就是你提取的类对应不上你unet生成的，最好是找到当时unet生成时对应的label关系
